module.exports = [
    { title: "Prologue", povCharacter: "Varamyr Sixskins", order: 1 },
    { title: "Tyrion I", povCharacter: "Tyrion Lannister", order: 2 },
    { title: "Daenerys I", povCharacter: "Daenerys Targaryen", order: 3 },
    { title: "Jon I", povCharacter: "Jon Snow", order: 4 },
    { title: "Bran I", povCharacter: "Bran Stark", order: 5 },
    { title: "Tyrion II", povCharacter: "Tyrion Lannister", order: 6 },
    { title: "Daenerys II", povCharacter: "Daenerys Targaryen", order: 7 },
    { title: "Jon II", povCharacter: "Jon Snow", order: 8 },
    { title: "Davos I", povCharacter: "Davos Seaworth", order: 9 },
    { title: "Reek I", povCharacter: "Theon Greyjoy", order: 10 },
    { title: "Bran II", povCharacter: "Bran Stark", order: 11 },
    { title: "Tyrion III", povCharacter: "Tyrion Lannister", order: 12 },
    { title: "Daenerys III", povCharacter: "Daenerys Targaryen", order: 13 },
    { title: "Jon III", povCharacter: "Jon Snow", order: 14 },
    { title: "Davos II", povCharacter: "Davos Seaworth", order: 15 },
    { title: "Reek II", povCharacter: "Theon Greyjoy", order: 16 },
    { title: "Bran III", povCharacter: "Bran Stark", order: 17 },
    { title: "Tyrion IV", povCharacter: "Tyrion Lannister", order: 18 },
    { title: "Daenerys IV", povCharacter: "Daenerys Targaryen", order: 19 },
    { title: "Jon IV", povCharacter: "Jon Snow", order: 20 },
        { title: "Tyrion V", povCharacter: "Tyrion Lannister", order: 21 },
    { title: "Davos III", povCharacter: "Davos Seaworth", order: 22 },
    { title: "Reek II", povCharacter: "Theon Greyjoy", order: 23 },
    { title: "Jon V", povCharacter: "Jon Snow", order: 24 },
    { title: "Tyrion VI", povCharacter: "Tyrion Lannister", order: 25 },
    { title: "Daenerys IV", povCharacter: "Daenerys Targaryen", order: 26 },
    { title: "The Lost Lord", povCharacter: "Jon Connington", order: 27 },
    { title: "The Windblown", povCharacter: "Quentyn Martell", order: 28 },
    { title: "The Wayward Bride", povCharacter: "Asha Greyjoy", order: 29 },
    { title: "Tyrion VII", povCharacter: "Tyrion Lannister", order: 30 },
    { title: "Jon VI", povCharacter: "Jon Snow", order: 31 },
    { title: "Davos IV", povCharacter: "Davos Seaworth", order: 32 },
    { title: "Daenerys V", povCharacter: "Daenerys Targaryen", order: 33 },
    { title: "Melisandre", povCharacter: "Melisandre", order: 34 },
    { title: "Reek III", povCharacter: "Theon Greyjoy", order: 35 },
    { title: "Tyrion VIII", povCharacter: "Tyrion Lannister", order: 36 },
    { title: "Bran III", povCharacter: "Bran Stark", order: 37 },
    { title: "Jon VII", povCharacter: "Jon Snow", order: 38 },
    { title: "Daenerys VI", povCharacter: "Daenerys Targaryen", order: 39 },
    { title: "The Prince of Winterfell", povCharacter: "Theon Greyjoy", order: 40 },
        { title: "The Watcher", povCharacter: "Areo Hotah", order: 41 },
    { title: "Jon VIII", povCharacter: "Jon Snow", order: 42 },
    { title: "Tyrion IX", povCharacter: "Tyrion Lannister", order: 43 },
    { title: "The Turncloak", povCharacter: "Theon Greyjoy", order: 44 },
    { title: "The King's Prize", povCharacter: "Asha Greyjoy", order: 45 },
    { title: "Daenerys VII", povCharacter: "Daenerys Targaryen", order: 46 },
    { title: "Jon IX", povCharacter: "Jon Snow", order: 47 },
    { title: "The Blind Girl", povCharacter: "Arya Stark", order: 48 },
    { title: "A Ghost in Winterfell", povCharacter: "Theon Greyjoy", order: 49 },
    { title: "Tyrion X", povCharacter: "Tyrion Lannister", order: 50 },
    { title: "Jaime I", povCharacter: "Jaime Lannister", order: 51 },
    { title: "Jon X", povCharacter: "Jon Snow", order: 52 },
    { title: "Daenerys VIII", povCharacter: "Daenerys Targaryen", order: 53 },
    { title: "The Queensguard", povCharacter: "Barristan Selmy", order: 54 },
    { title: "The Iron Suitor", povCharacter: "Victarion Greyjoy", order: 55 },
    { title: "Tyrion XI", povCharacter: "Tyrion Lannister", order: 56 },
    { title: "The Discarded Knight", povCharacter: "Barristan Selmy", order: 57 },
    { title: "The Spurned Suitor", povCharacter: "Quentyn Martell", order: 58 },
    { title: "The Griffin Reborn", povCharacter: "Jon Connington", order: 59 },
    { title: "The Sacrifice", povCharacter: "Asha Greyjoy", order: 60 },
        { title: "Victarion I", povCharacter: "Victarion Greyjoy", order: 61 },
    { title: "The Ugly Little Girl", povCharacter: "Arya Stark", order: 62 },
    { title: "Cersei II", povCharacter: "Cersei Lannister", order: 63 },
    { title: "Tyrion XII", povCharacter: "Tyrion Lannister", order: 64 },
    { title: "The Kingbreaker", povCharacter: "Barristan Selmy", order: 65 },
    { title: "The Dragontamer", povCharacter: "Quentyn Martell", order: 66 },
    { title: "Jon XIII", povCharacter: "Jon Snow", order: 67 },
    { title: "The Queen's Hand", povCharacter: "Barristan Selmy", order: 68 },
    { title: "Daenerys X", povCharacter: "Daenerys Targaryen", order: 69 },
    { title: "Epilogue", povCharacter: "Kevan Lannister", order: 70 }
];
