module.exports = [
    { title: "Prologue", povCharacter: "Pate", order: 1 },
    { title: "The Prophet", povCharacter: "Aeron Greyjoy", order: 2 },
    { title: "The Captain Of Guards", povCharacter: "Areo Hotah", order: 3 },
    { title: "Cersei I", povCharacter: "Cersei Lannister", order: 4 },
    { title: "Brienne I", povCharacter: "Brienne of Tarth", order: 5 },
    { title: "Samwell I", povCharacter: "Samwell Tarly", order: 6 },
    { title: "Arya I", povCharacter: "Arya Stark", order: 7 },
    { title: "Cersei II", povCharacter: "Cersei Lannister", order: 8 },
    { title: "Jaime I", povCharacter: "Jaime Lannister", order: 9 },
    { title: "Brienne II", povCharacter: "Brienne of Tarth", order: 10 },
    { title: "Sansa I", povCharacter: "Sansa Stark", order: 11 },
    { title: "The Kraken's Daughter", povCharacter: "Asha Greyjoy", order: 12 },
    { title: "Cersei III", povCharacter: "Cersei Lannister", order: 13 },
    { title: "The Soiled Knight", povCharacter: "Arys Oakheart", order: 14 },
    { title: "Brienne III", povCharacter: "Brienne of Tarth", order: 15 },
    { title: "Samwell II", povCharacter: "Samwell Tarly", order: 16 },
    { title: "Jaime II", povCharacter: "Jaime Lannister", order: 17 },
    { title: "Cersei IV", povCharacter: "Cersei Lannister", order: 18 },
    { title: "The Iron Captain", povCharacter: "Victarion Greyjoy", order: 19 },
    { title: "The Drowned Man", povCharacter: "Aeron Greyjoy", order: 20 },
    { title: "Brienne IV", povCharacter: "Brienne of Tarth", order: 21 },
    { title: "The Queenmaker", povCharacter: "Arys Oakheart", order: 22 },
    { title: "Arya II", povCharacter: "Arya Stark", order: 23 },
    { title: "Alayne I", povCharacter: "Alayne Stone", order: 24 },
    { title: "Cersei V", povCharacter: "Cersei Lannister", order: 25 },
    { title: "Brienne V", povCharacter: "Brienne of Tarth", order: 26 },
    { title: "Samwell III", povCharacter: "Samwell Tarly", order: 27 },
    { title: "Jaime III", povCharacter: "Jaime Lannister", order: 28 },
    { title: "Cersei VI", povCharacter: "Cersei Lannister", order: 29 },
    { title: "The Reaver", povCharacter: "Victarion Greyjoy", order: 30 },
    { title: "Jaime IV", povCharacter: "Jaime Lannister", order: 31 },
    { title: "Brienne VI", povCharacter: "Brienne of Tarth", order: 32 },
    { title: "Cersei VII", povCharacter: "Cersei Lannister", order: 33 },
    { title: "Jaime V", povCharacter: "Jaime Lannister", order: 34 },
    { title: "Cat Of The Canals", povCharacter: "Arya Stark", order: 35 },
    { title: "Samwell IV", povCharacter: "Samwell Tarly", order: 36 },
    { title: "Cersei VIII", povCharacter: "Cersei Lannister", order: 37 },
    { title: "Brienne VII", povCharacter: "Brienne of Tarth", order: 38 },
    { title: "Jaime VI", povCharacter: "Jaime Lannister", order: 39 },
    { title: "Cersei IX", povCharacter: "Cersei Lannister", order: 40 },
    { title: "The Princess In The Tower", povCharacter: "Arianne Martell", order: 41 },
    { title: "Alayne II", povCharacter: "Alayne Stone", order: 42 },
    { title: "Brienne VIII", povCharacter: "Brienne of Tarth", order: 43 },
    { title: "Cersei X", povCharacter: "Cersei Lannister", order: 44 },
    { title: "Jaime VII", povCharacter: "Jaime Lannister", order: 45 },
    { title: "Samwell V", povCharacter: "Samwell Tarly", order: 46 }
];